"""Export the current vendor data as portable SQL for the prod cutover.

Dumps every vendor row + their trade specializations + any
Brenk-only custom trades, with `sc_user_id` blanked and the auto-
increment `id` re-assigned in the destination. Output is a single
transactional SQL script that can be piped into the production
Supabase database via psql.

Runbook at cutover:

  1. Provision production Supabase, run `alembic upgrade head` against
     it, and start the worker so a first work-order sync populates
     `trades` from production SC.
  2. From this dev environment:
       python scripts/export_vendors_for_cutover.py > vendors.sql
  3. Pipe into production:
       psql "$PROD_DATABASE_URL" < vendors.sql
  4. In the dashboard, click "Sync from ServiceChannel" on the
     Vendors page. The email-fallback in `sync_vendors_from_sc` will
     match each imported row to its production SC user and fill in
     `sc_user_id`. Daryl's notes survive untouched.

Notes on what's included / excluded:

  * `id`, `sc_user_id`, `sc_provider_id`, `raw_data`, `created_at`,
    `updated_at` are NOT exported — they're environment-local or
    auto-populated.
  * Inactive vendors (`is_active = false`) are included; you can
    delete those rows from the .sql file if you'd rather skip them.
  * Vendors with duplicate emails are flagged in a comment — the
    email-fallback at prod-sync time picks the first match, so two
    rows sharing an email may not both get their `sc_user_id`.
  * Brenk-only trades (no `sc_trade_id`) are emitted as
    `INSERT ... ON CONFLICT (name) DO NOTHING` so the script is safe
    to re-run.
"""

import asyncio
import logging
import sys
from collections import Counter

from sqlalchemy import select
from sqlalchemy.orm import selectinload

from app.db.session import AsyncSessionLocal
from app.models.work_order import Trade, Vendor

# DEBUG=true turns on SQLAlchemy echo, which spews every query to stderr.
# Useful in dev, noisy when the operator is exporting. Mute it for this
# script so `python … > vendors.sql` produces a clean log on the console.
logging.getLogger("sqlalchemy.engine").setLevel(logging.WARNING)


def _sql_literal(value: object) -> str:
    """Render a Python value as a Postgres literal."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    # String: single-quote and escape any embedded apostrophes.
    return "'" + str(value).replace("'", "''") + "'"


def _quoted_name_list(names: list[str]) -> str:
    return ", ".join(_sql_literal(n) for n in names)


async def main() -> None:
    out = sys.stdout.write

    out("-- ============================================================\n")
    out("-- Brenk Operating Platform — vendor cutover export\n")
    out("-- ============================================================\n")
    out("-- Generated by backend/scripts/export_vendors_for_cutover.py\n")
    out("-- Run AGAINST PRODUCTION SUPABASE.\n")
    out("-- See the docstring of that script for the full runbook.\n")
    out("--\n")
    out("-- WARNING: this is intended to be run once, on an empty\n")
    out("-- production `vendors` table. There's no de-duplication on\n")
    out("-- vendors — running twice creates duplicates.\n")
    out("--\n\n")

    async with AsyncSessionLocal() as session:
        # ---------- Custom (Brenk-only) trades -------------------------
        custom_trades = (
            await session.execute(
                select(Trade)
                .where(Trade.sc_trade_id.is_(None))
                .order_by(Trade.name.asc())
            )
        ).scalars().all()

        out("BEGIN;\n\n")

        if custom_trades:
            out("-- Brenk-only custom trades (no SC counterpart).\n")
            out("-- Safe to re-run thanks to ON CONFLICT DO NOTHING.\n")
            for t in custom_trades:
                out(
                    "INSERT INTO trades (name) VALUES "
                    f"({_sql_literal(t.name)}) "
                    "ON CONFLICT (name) DO NOTHING;\n"
                )
            out("\n")

        # ---------- Vendors -------------------------------------------
        vendors = list(
            (
                await session.execute(
                    select(Vendor)
                    .options(selectinload(Vendor.trade_specializations))
                    .order_by(Vendor.name.asc(), Vendor.id.asc())
                )
            ).scalars()
        )

        out(f"-- {len(vendors)} vendor row(s) follow.\n\n")

        # Flag duplicate emails so the operator knows the prod-sync
        # email-fallback may not match all of them.
        email_counts = Counter(
            (v.email or "").lower() for v in vendors if v.email
        )
        dupe_emails = [e for e, n in email_counts.items() if n > 1]
        if dupe_emails:
            out("-- WARNING: the following emails appear on more than one row.\n")
            out("--   On prod sync, the email-fallback picks the first match,\n")
            out("--   so the other rows will keep their sc_user_id NULL until\n")
            out("--   you manually edit them.\n")
            for e in sorted(dupe_emails):
                out(f"--   - {e}  (n={email_counts[e]})\n")
            out("\n")

        # Columns we export — explicitly NOT including id / sc_user_id /
        # sc_provider_id / raw_data / created_at / updated_at.
        export_columns = [
            "name",
            "phone",
            "email",
            "notes",
            "is_active",
            "contact_preference",
            "payment_terms",
            "service_area",
            "mobile_app_capable",
            "markup_notes",
            "communication_notes",
        ]

        for vendor in vendors:
            values = [getattr(vendor, col) for col in export_columns]
            cols_sql = ", ".join(export_columns)
            vals_sql = ", ".join(_sql_literal(v) for v in values)
            trade_names = [t.name for t in vendor.trade_specializations]

            out(f"-- Vendor: {vendor.name}\n")
            if trade_names:
                # CTE-style insert: insert vendor + capture new id, then
                # link trades by name. Works regardless of what prod's
                # trade ids are.
                out("WITH new_vendor AS (\n")
                out(f"  INSERT INTO vendors ({cols_sql})\n")
                out(f"  VALUES ({vals_sql})\n")
                out("  RETURNING id\n")
                out(")\n")
                out("INSERT INTO vendor_trades (vendor_id, trade_id)\n")
                out("SELECT new_vendor.id, trades.id\n")
                out("FROM new_vendor, trades\n")
                out(f"WHERE trades.name IN ({_quoted_name_list(trade_names)});\n")
            else:
                out(f"INSERT INTO vendors ({cols_sql}) VALUES ({vals_sql});\n")
            out("\n")

        out("COMMIT;\n")


if __name__ == "__main__":
    asyncio.run(main())
