"""storefront content + services tables

Revision ID: 09c90c8c66fc
Revises: 7fcd05173cd8
Create Date: 2026-05-25 15:08:34.884710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09c90c8c66fc"
down_revision: Union[str, Sequence[str], None] = "7fcd05173cd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storefront_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hero_title", sa.String(length=200), nullable=True),
        sa.Column("hero_subtitle", sa.String(length=500), nullable=True),
        sa.Column("hero_cta_text", sa.String(length=100), nullable=True),
        sa.Column("hero_cta_link", sa.String(length=500), nullable=True),
        sa.Column("hero_image_url", sa.String(length=1000), nullable=True),
        sa.Column("about_heading", sa.String(length=200), nullable=True),
        sa.Column("about_body", sa.Text(), nullable=True),
        sa.Column("about_image_url", sa.String(length=1000), nullable=True),
        sa.Column("service_area_heading", sa.String(length=200), nullable=True),
        sa.Column("service_area_body", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("contact_address", sa.String(length=500), nullable=True),
        sa.Column("contact_hours", sa.String(length=200), nullable=True),
        sa.Column("footer_tagline", sa.String(length=300), nullable=True),
        sa.Column("footer_copyright", sa.String(length=200), nullable=True),
        sa.Column("logo_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "storefront_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["content_id"], ["storefront_content.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_storefront_services_content_id"),
        "storefront_services",
        ["content_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storefront_services_content_id"), table_name="storefront_services")
    op.drop_table("storefront_services")
    op.drop_table("storefront_content")
    # ### end Alembic commands ###
