"""work order brenk category fields

Revision ID: 18696c6a6a76
Revises: b9f20eb0f4b7
Create Date: 2026-06-22 20:21:24.759697

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18696c6a6a76"
down_revision: str | Sequence[str] | None = "b9f20eb0f4b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("work_orders", sa.Column("brenk_category", sa.String(length=50), nullable=True))
    op.add_column(
        "work_orders", sa.Column("brenk_category_source", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "work_orders",
        sa.Column("brenk_category_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
    )
    op.add_column(
        "work_orders", sa.Column("brenk_category_ai", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "work_orders", sa.Column("brenk_category_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_work_orders_brenk_category"), "work_orders", ["brenk_category"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_orders_brenk_category"), table_name="work_orders")
    op.drop_column("work_orders", "brenk_category_at")
    op.drop_column("work_orders", "brenk_category_ai")
    op.drop_column("work_orders", "brenk_category_confidence")
    op.drop_column("work_orders", "brenk_category_source")
    op.drop_column("work_orders", "brenk_category")
    # ### end Alembic commands ###
