"""invoice queue: markup + paid columns

Revision ID: 296975eb2cc3
Revises: e7a62fa80b56
Create Date: 2026-05-25 12:56:05.917105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "296975eb2cc3"
down_revision: Union[str, Sequence[str], None] = "e7a62fa80b56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trades",
        sa.Column("default_markup_percent", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "work_orders",
        sa.Column("brenk_markup_percent", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "work_orders", sa.Column("brenk_marked_up_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "work_orders", sa.Column("brenk_paid_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_orders", "brenk_paid_at")
    op.drop_column("work_orders", "brenk_marked_up_at")
    op.drop_column("work_orders", "brenk_markup_percent")
    op.drop_column("trades", "default_markup_percent")
    # ### end Alembic commands ###
