"""invoice webhook sync tables

Revision ID: 2a505b1717a0
Revises: faf100f05a60
Create Date: 2026-06-10 17:22:19.355004

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a505b1717a0"
down_revision: str | Sequence[str] | None = "faf100f05a60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_labors",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("sc_env", sa.String(length=20), nullable=False),
        sa.Column("sc_invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("skill_level", sa.Integer(), nullable=True),
        sa.Column("labor_type", sa.Integer(), nullable=True),
        sa.Column("num_of_tech", sa.Integer(), nullable=True),
        sa.Column("hourly_rate", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("hours", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_invoice_labors_invoice", "invoice_labors", ["sc_env", "sc_invoice_id"], unique=False
    )
    op.create_table(
        "invoice_materials",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("sc_env", sa.String(length=20), nullable=False),
        sa.Column("sc_invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("part_num", sa.String(length=100), nullable=True),
        sa.Column("unit_type", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_invoice_materials_invoice",
        "invoice_materials",
        ["sc_env", "sc_invoice_id"],
        unique=False,
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("sc_invoice_id", sa.BigInteger(), nullable=True),
        sa.Column("sc_env", sa.String(length=20), nullable=False),
        sa.Column("invoice_number", sa.String(length=100), nullable=False),
        sa.Column("wo_tracking_number", sa.BigInteger(), nullable=True),
        sa.Column("subscriber_id", sa.BigInteger(), nullable=True),
        sa.Column("provider_id", sa.BigInteger(), nullable=True),
        sa.Column("location_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("trade", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("invoice_tax", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("invoice_total", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("approval_code", sa.String(length=80), nullable=True),
        sa.Column("batch_number", sa.String(length=80), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("invoice_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_action_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sc_updated_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_invoices_wo_tracking_number", "invoices", ["wo_tracking_number"], unique=False
    )
    op.create_index(
        "uq_invoices_number_wo",
        "invoices",
        ["sc_env", "invoice_number", sa.literal_column("coalesce(wo_tracking_number, -1)")],
        unique=True,
    )
    op.create_index(
        "uq_invoices_sc_invoice_id",
        "invoices",
        ["sc_env", "sc_invoice_id"],
        unique=True,
        postgresql_where=sa.text("sc_invoice_id IS NOT NULL"),
    )
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("sc_env", sa.String(length=20), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("raw_body", sa.LargeBinary(), nullable=False),
        sa.Column("sign_data", sa.Text(), nullable=True),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=True),
        sa.Column("object_id", sa.BigInteger(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=30), server_default="pending", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(
        "ix_webhook_events_pending",
        "webhook_events",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "invoice_status_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("sc_env", sa.String(length=20), nullable=False),
        sa.Column("sc_invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=True),
        sa.Column("changed_by", sa.String(length=200), nullable=True),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("webhook_event_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["webhook_event_id"],
            ["webhook_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_invoice_status_history_invoice",
        "invoice_status_history",
        ["sc_env", "sc_invoice_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Enable RLS on the new tables (same posture as faf100f05a60): the
    # backend connects as postgres/bypassrls, so this only denies the
    # Supabase Data API roles. New public tables must opt in or the
    # Supabase advisor flags them.
    for table in (
        "webhook_events",
        "invoices",
        "invoice_labors",
        "invoice_materials",
        "invoice_status_history",
    ):
        op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_invoice_status_history_invoice", table_name="invoice_status_history")
    op.drop_table("invoice_status_history")
    op.drop_index(
        "ix_webhook_events_pending",
        table_name="webhook_events",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("webhook_events")
    op.drop_index(
        "uq_invoices_sc_invoice_id",
        table_name="invoices",
        postgresql_where=sa.text("sc_invoice_id IS NOT NULL"),
    )
    op.drop_index("uq_invoices_number_wo", table_name="invoices")
    op.drop_index("ix_invoices_wo_tracking_number", table_name="invoices")
    op.drop_table("invoices")
    op.drop_index("ix_invoice_materials_invoice", table_name="invoice_materials")
    op.drop_table("invoice_materials")
    op.drop_index("ix_invoice_labors_invoice", table_name="invoice_labors")
    op.drop_table("invoice_labors")
    # ### end Alembic commands ###
