"""customer-unit access flag columns

Revision ID: 3f1cd1fcda86
Revises: e539527d12f6
Create Date: 2026-07-06 22:48:51.586312

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f1cd1fcda86"
down_revision: str | Sequence[str] | None = "e539527d12f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_orders", sa.Column("brenk_access_flag_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "work_orders", sa.Column("brenk_access_flag_source", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "work_orders", sa.Column("brenk_access_flag_note_id", sa.BigInteger(), nullable=True)
    )
    op.add_column("work_orders", sa.Column("brenk_access_flag_snippet", sa.Text(), nullable=True))
    op.add_column(
        "work_orders",
        sa.Column("brenk_access_flag_dismissed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "work_orders",
        sa.Column("brenk_access_scheduled_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_orders", "brenk_access_scheduled_at")
    op.drop_column("work_orders", "brenk_access_flag_dismissed_at")
    op.drop_column("work_orders", "brenk_access_flag_snippet")
    op.drop_column("work_orders", "brenk_access_flag_note_id")
    op.drop_column("work_orders", "brenk_access_flag_source")
    op.drop_column("work_orders", "brenk_access_flag_at")
    # ### end Alembic commands ###
