"""wo_vendor_assignments multi-vendor

Revision ID: 5bced7798969
Revises: c9848d142f20
Create Date: 2026-06-27 16:59:46.184463

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bced7798969"
down_revision: str | Sequence[str] | None = "c9848d142f20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wo_vendor_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_order_id", sa.Integer(), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("job_type_id", sa.Integer(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_type_id"],
            ["job_types.id"],
        ),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_order_id"], ["work_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_order_id", "vendor_id", name="uq_wo_vendor"),
    )
    op.create_index(
        op.f("ix_wo_vendor_assignments_vendor_id"),
        "wo_vendor_assignments",
        ["vendor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wo_vendor_assignments_work_order_id"),
        "wo_vendor_assignments",
        ["work_order_id"],
        unique=False,
    )

    op.execute("ALTER TABLE public.wo_vendor_assignments ENABLE ROW LEVEL SECURITY")

    # Backfill: every WO with a (single) assigned vendor becomes one assignment
    # row, carrying its per-WO notified timestamp. assigned_vendor_id stays as
    # the synced primary for back-compat.
    op.execute(
        """
        INSERT INTO wo_vendor_assignments
            (work_order_id, vendor_id, notified_at, created_at, updated_at)
        SELECT id, assigned_vendor_id, brenk_vendor_notified_at, now(), now()
        FROM work_orders
        WHERE assigned_vendor_id IS NOT NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wo_vendor_assignments_work_order_id"), table_name="wo_vendor_assignments"
    )
    op.drop_index(op.f("ix_wo_vendor_assignments_vendor_id"), table_name="wo_vendor_assignments")
    op.drop_table("wo_vendor_assignments")
    # ### end Alembic commands ###
