"""expand vendors + add vendor_trades junction

Revision ID: 65dc81727adf
Revises: 9a84643a059f
Create Date: 2026-05-19 17:54:13.957922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65dc81727adf"
down_revision: Union[str, Sequence[str], None] = "9a84643a059f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_trades",
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("vendor_id", "trade_id"),
    )
    op.add_column("vendors", sa.Column("contact_preference", sa.String(length=20), nullable=True))
    op.add_column("vendors", sa.Column("payment_terms", sa.String(length=100), nullable=True))
    op.add_column("vendors", sa.Column("mobile_app_capable", sa.Boolean(), nullable=True))
    op.add_column("vendors", sa.Column("markup_notes", sa.Text(), nullable=True))
    op.add_column("vendors", sa.Column("communication_notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendors", "communication_notes")
    op.drop_column("vendors", "markup_notes")
    op.drop_column("vendors", "mobile_app_capable")
    op.drop_column("vendors", "payment_terms")
    op.drop_column("vendors", "contact_preference")
    op.drop_table("vendor_trades")
    # ### end Alembic commands ###
