"""split brenk vendor cost into labor + material

Revision ID: 7fcd05173cd8
Revises: 296975eb2cc3
Create Date: 2026-05-25 13:19:22.199209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fcd05173cd8"
down_revision: Union[str, Sequence[str], None] = "296975eb2cc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_orders",
        sa.Column("brenk_labor_cost", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "work_orders",
        sa.Column("brenk_material_cost", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_orders", "brenk_material_cost")
    op.drop_column("work_orders", "brenk_labor_cost")
    # ### end Alembic commands ###
