"""work_orders sc_invoice_total

Revision ID: 93c84ffb76c3
Revises: f7991cf106d2
Create Date: 2026-06-10 19:00:42.561116

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93c84ffb76c3"
down_revision: str | Sequence[str] | None = "f7991cf106d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_orders",
        sa.Column("sc_invoice_total", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_orders", "sc_invoice_total")
    # ### end Alembic commands ###
