"""initial schema

Revision ID: 9a84643a059f
Revises:
Create Date: 2026-05-16 12:38:14.474071

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a84643a059f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sc_subscriber_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=255), nullable=True),
        sa.Column("is_outsourced", sa.Boolean(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clients_sc_subscriber_id"), "clients", ["sc_subscriber_id"], unique=True
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sc_trade_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_trades_sc_trade_id"), "trades", ["sc_trade_id"], unique=True)
    op.create_table(
        "vendors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sc_provider_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vendors_sc_provider_id"), "vendors", ["sc_provider_id"], unique=True)
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sc_location_id", sa.BigInteger(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("region", sa.String(length=50), nullable=True),
        sa.Column("district", sa.String(length=50), nullable=True),
        sa.Column("timezone_offset", sa.Integer(), nullable=True),
        sa.Column("is_international", sa.Boolean(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_locations_client_id"), "locations", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_locations_sc_location_id"), "locations", ["sc_location_id"], unique=True
    )
    op.create_index(op.f("ix_locations_store_id"), "locations", ["store_id"], unique=False)
    op.create_table(
        "work_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sc_work_order_id", sa.BigInteger(), nullable=False),
        sa.Column("sc_number", sa.String(length=50), nullable=False),
        sa.Column("sc_purchase_number", sa.String(length=50), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("trade_id", sa.Integer(), nullable=True),
        sa.Column("assigned_vendor_id", sa.Integer(), nullable=True),
        sa.Column("primary_status", sa.String(length=50), nullable=False),
        sa.Column("extended_status", sa.String(length=100), nullable=True),
        sa.Column("can_create_invoice", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("sc_category_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.String(length=100), nullable=True),
        sa.Column("problem_code", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("caller", sa.String(length=255), nullable=True),
        sa.Column("approval_code", sa.String(length=50), nullable=True),
        sa.Column("nte", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("call_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_eta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sc_updated_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_invoiced", sa.Boolean(), nullable=False),
        sa.Column("is_expired", sa.Boolean(), nullable=False),
        sa.Column("is_check_in_denied", sa.Boolean(), nullable=False),
        sa.Column("has_work_activity", sa.Boolean(), nullable=False),
        sa.Column("auto_complete", sa.Boolean(), nullable=False),
        sa.Column("auto_invoice", sa.Boolean(), nullable=False),
        sa.Column("notes_count", sa.Integer(), nullable=False),
        sa.Column("attachments_count", sa.Integer(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "last_synced_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_vendor_id"],
            ["vendors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_orders_assigned_vendor_id"),
        "work_orders",
        ["assigned_vendor_id"],
        unique=False,
    )
    op.create_index(op.f("ix_work_orders_client_id"), "work_orders", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_work_orders_location_id"), "work_orders", ["location_id"], unique=False
    )
    op.create_index(
        "ix_work_orders_primary_status", "work_orders", ["primary_status"], unique=False
    )
    op.create_index(op.f("ix_work_orders_sc_number"), "work_orders", ["sc_number"], unique=False)
    op.create_index(
        "ix_work_orders_sc_updated_date", "work_orders", ["sc_updated_date"], unique=False
    )
    op.create_index(
        op.f("ix_work_orders_sc_work_order_id"), "work_orders", ["sc_work_order_id"], unique=True
    )
    op.create_index(
        "ix_work_orders_scheduled_date", "work_orders", ["scheduled_date"], unique=False
    )
    op.create_index(op.f("ix_work_orders_trade_id"), "work_orders", ["trade_id"], unique=False)
    op.create_table(
        "wo_notes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("work_order_id", sa.Integer(), nullable=False),
        sa.Column("sc_note_id", sa.BigInteger(), nullable=True),
        sa.Column("sc_document_id", sa.String(length=64), nullable=True),
        sa.Column("note_number", sa.Integer(), nullable=True),
        sa.Column("note_data", sa.Text(), nullable=False),
        sa.Column("note_type", sa.String(length=50), nullable=True),
        sa.Column("visibility", sa.Integer(), nullable=True),
        sa.Column("action_required", sa.Boolean(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("is_attachment_note", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("created_at_sc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sc_note_id", name="uq_wo_notes_sc_note_id"),
    )
    op.create_index("ix_wo_notes_work_order_id", "wo_notes", ["work_order_id"], unique=False)
    op.create_table(
        "wo_status_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("work_order_id", sa.Integer(), nullable=False),
        sa.Column("primary_status", sa.String(length=50), nullable=False),
        sa.Column("extended_status", sa.String(length=100), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("changed_by", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_wo_status_history_work_order_id", "wo_status_history", ["work_order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wo_status_history_work_order_id", table_name="wo_status_history")
    op.drop_table("wo_status_history")
    op.drop_index("ix_wo_notes_work_order_id", table_name="wo_notes")
    op.drop_table("wo_notes")
    op.drop_index(op.f("ix_work_orders_trade_id"), table_name="work_orders")
    op.drop_index("ix_work_orders_scheduled_date", table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_sc_work_order_id"), table_name="work_orders")
    op.drop_index("ix_work_orders_sc_updated_date", table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_sc_number"), table_name="work_orders")
    op.drop_index("ix_work_orders_primary_status", table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_location_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_client_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_assigned_vendor_id"), table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_index(op.f("ix_locations_store_id"), table_name="locations")
    op.drop_index(op.f("ix_locations_sc_location_id"), table_name="locations")
    op.drop_index(op.f("ix_locations_client_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_vendors_sc_provider_id"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index(op.f("ix_trades_sc_trade_id"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_clients_sc_subscriber_id"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
