"""add job_types taxonomy table

Revision ID: a055973d971a
Revises: 18696c6a6a76
Create Date: 2026-06-27 15:33:34.516122

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a055973d971a"
down_revision: str | Sequence[str] | None = "18696c6a6a76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Initial taxonomy snapshot (name, description, is_catchall) in display order.
# Today's 16 categories + Windows & Glass, Appliance Repair, Parking Lot
# Striping (distinct trades that were being lost) + Locksmith, Security (real
# SC job trades with no prior category). Daryl edits the live list in-app, so
# this is only the starting point.
_SEED: list[tuple[str, str, bool]] = [
    ("Electrical", "Wiring, outlets, lighting, panels, electrical repairs.", False),
    ("Plumbing", "Leaks, drains, pipes, water heaters, fixtures, backflow.", False),
    ("Roofing", "Roof leaks, membrane, flashing, roof repair/replacement.", False),
    ("Doors", "Doors — roll-up, overhead, swing, hardware, openers.", False),
    ("Windows & Glass", "Windows, storefront glass, glazing, broken panes.", False),
    ("Gates & Access", "Gates, keypads, access control, gate motors/operators.", False),
    ("Fencing", "Fences, posts, perimeter repair (chain-link, wood).", False),
    ("HVAC", "Heating, cooling, ventilation, thermostats, AC units.", False),
    ("Appliance Repair", "Appliances — refrigeration, laundry, kitchen equipment.", False),
    ("Flooring", "Floors, tile, carpet, concrete floor finishes.", False),
    ("Painting", "Interior/exterior painting, coatings, surface prep.", False),
    ("Drywall", "Drywall / sheet rock — hang, patch, texture, repair.", False),
    ("General Building", "General carpentry/handyman/interior building repairs.", False),
    ("Exterior Building", "Exterior walls, siding, gutters, soffit, stucco.", False),
    ("Trash Removal", "Bulk trash, junk hauling, debris/dumpster removal.", False),
    ("Concrete & Asphalt", "Concrete, asphalt, sidewalks, curbs (not striping).", False),
    ("Parking Lot Striping", "Pavement striping, markings, stenciling.", False),
    ("Landscaping", "Landscaping, grounds, irrigation, tree/shrub work.", False),
    ("Pest Control", "Pest, rodent, insect control and exclusion.", False),
    ("Locksmith", "Locks, rekeying, keys, lock hardware.", False),
    ("Security", "Cameras, alarms, security systems, monitoring.", False),
    ("Other", "Anything that doesn't clearly fit another type.", True),
]


def upgrade() -> None:
    job_types = op.create_table(
        "job_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_catchall", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.bulk_insert(
        job_types,
        [
            {
                "name": name,
                "description": desc,
                "position": i,
                "is_active": True,
                "is_catchall": catchall,
            }
            for i, (name, desc, catchall) in enumerate(_SEED)
        ],
    )

    # Match the project's security posture (backend role is bypassrls; the
    # Supabase Data API is disabled — this satisfies the RLS advisor).
    op.execute("ALTER TABLE public.job_types ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_types")
    # ### end Alembic commands ###
