"""add work_orders.brenk_vendor_notified_at

Revision ID: a596be059b27
Revises: 09c90c8c66fc
Create Date: 2026-06-01 22:29:15.988352

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a596be059b27"
down_revision: str | Sequence[str] | None = "09c90c8c66fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_orders",
        sa.Column("brenk_vendor_notified_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_orders", "brenk_vendor_notified_at")
    # ### end Alembic commands ###
