"""locations enrichment + gate_codes table

Revision ID: b9f20eb0f4b7
Revises: a1b2c3d4e5f6
Create Date: 2026-06-20 13:30:57.129631

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9f20eb0f4b7"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gate_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_gate_codes_location_active",
        "gate_codes",
        ["location_id"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index("ix_gate_codes_location_id", "gate_codes", ["location_id"], unique=False)
    op.add_column(
        "locations", sa.Column("district_manager_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "locations", sa.Column("district_manager_phone", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "locations", sa.Column("district_manager_email", sa.String(length=255), nullable=True)
    )
    op.add_column("locations", sa.Column("rating", sa.String(length=20), nullable=True))
    op.add_column("locations", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # New public tables must have RLS enabled (Supabase advisor); the
    # backend connects as postgres/bypassrls so this is a no-op for us but
    # closes the rls_disabled_in_public finding. The added `locations`
    # columns inherit that table's existing RLS. RLS on gate_codes
    # disappears automatically when the table is dropped in downgrade().
    op.execute("ALTER TABLE public.gate_codes ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "description")
    op.drop_column("locations", "rating")
    op.drop_column("locations", "district_manager_email")
    op.drop_column("locations", "district_manager_phone")
    op.drop_column("locations", "district_manager_name")
    op.drop_index("ix_gate_codes_location_id", table_name="gate_codes")
    op.drop_index(
        "ix_gate_codes_location_active",
        table_name="gate_codes",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("gate_codes")
    # ### end Alembic commands ###
