"""vendor_job_types link table

Revision ID: c9848d142f20
Revises: a055973d971a
Create Date: 2026-06-27 16:04:44.680804

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9848d142f20"
down_revision: str | Sequence[str] | None = "a055973d971a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_job_types",
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("job_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_type_id"], ["job_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("vendor_id", "job_type_id"),
    )
    op.execute("ALTER TABLE public.vendor_job_types ENABLE ROW LEVEL SECURITY")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vendor_job_types")
    # ### end Alembic commands ###
