"""assignment payouts + paid_to_vendor

Revision ID: e539527d12f6
Revises: 5bced7798969
Create Date: 2026-06-27 18:42:09.231225

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e539527d12f6"
down_revision: str | Sequence[str] | None = "5bced7798969"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wo_vendor_assignments",
        sa.Column("labor_cost", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "wo_vendor_assignments",
        sa.Column("material_cost", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "wo_vendor_assignments",
        sa.Column("paid_to_vendor_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Backfill: move each WO's existing (single-vendor) labor/material cost onto
    # its primary (earliest) assignment. The WO-level fields remain as the
    # rollup sum, so invoice/money/markup math keep reading them unchanged.
    op.execute(
        """
        UPDATE wo_vendor_assignments a
        SET labor_cost = w.brenk_labor_cost,
            material_cost = w.brenk_material_cost
        FROM work_orders w
        WHERE a.work_order_id = w.id
          AND (w.brenk_labor_cost IS NOT NULL OR w.brenk_material_cost IS NOT NULL)
          AND a.id = (
              SELECT a2.id FROM wo_vendor_assignments a2
              WHERE a2.work_order_id = w.id
              ORDER BY a2.created_at ASC, a2.id ASC
              LIMIT 1
          )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wo_vendor_assignments", "paid_to_vendor_at")
    op.drop_column("wo_vendor_assignments", "material_cost")
    op.drop_column("wo_vendor_assignments", "labor_cost")
    # ### end Alembic commands ###
