"""add vendors.service_area

Revision ID: e7a62fa80b56
Revises: f44a3b1bb539
Create Date: 2026-05-19 23:08:50.945026

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7a62fa80b56"
down_revision: str | Sequence[str] | None = "f44a3b1bb539"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vendors", sa.Column("service_area", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendors", "service_area")
    # ### end Alembic commands ###
