"""add vendors.sc_user_id

Revision ID: f44a3b1bb539
Revises: 65dc81727adf
Create Date: 2026-05-19 22:25:52.675133

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f44a3b1bb539"
down_revision: str | Sequence[str] | None = "65dc81727adf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vendors", sa.Column("sc_user_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_vendors_sc_user_id"), "vendors", ["sc_user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vendors_sc_user_id"), table_name="vendors")
    op.drop_column("vendors", "sc_user_id")
    # ### end Alembic commands ###
