"""work_orders sc_invoice fields

Revision ID: f7991cf106d2
Revises: 2a505b1717a0
Create Date: 2026-06-10 17:38:54.775030

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7991cf106d2"
down_revision: str | Sequence[str] | None = "2a505b1717a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("work_orders", sa.Column("sc_invoice_id", sa.BigInteger(), nullable=True))
    op.add_column(
        "work_orders", sa.Column("sc_invoice_number", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "work_orders", sa.Column("sc_invoice_status", sa.String(length=40), nullable=True)
    )
    op.add_column(
        "work_orders",
        sa.Column("sc_invoice_submitted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("work_orders", sa.Column("sc_invoice_last_error", sa.Text(), nullable=True))
    op.add_column("work_orders", sa.Column("sc_paid_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_orders", "sc_paid_at")
    op.drop_column("work_orders", "sc_invoice_last_error")
    op.drop_column("work_orders", "sc_invoice_submitted_at")
    op.drop_column("work_orders", "sc_invoice_status")
    op.drop_column("work_orders", "sc_invoice_number")
    op.drop_column("work_orders", "sc_invoice_id")
    # ### end Alembic commands ###
